import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, ChevronRight, CircleHelp, Fingerprint, Globe2, HeartHandshake, MapPin, Plus, ScanSearch, Search, ShieldCheck, Sparkles, Wallet } from 'lucide-react';
import { useApp } from '../context/AppContext';
import ItemCard from '../components/ItemCard';

const services = [
  { icon: Search, title: '잃어버렸어요', text: '분실물을 등록하고 함께 찾아요', link: '/register?type=lost', tone: 'blue', label: '분실물 등록' },
  { icon: Wallet, title: '주인을 찾아요', text: '습득한 물건에 일상을 돌려주세요', link: '/register?type=found', tone: 'mint', label: '습득물 등록' },
  { icon: ScanSearch, title: 'AI가 찾아드려요', text: '내 물건과 닮은 후보를 만나보세요', link: '/matches', tone: 'purple', label: '매칭 추천' },
  { icon: Globe2, title: '전국을 한눈에', text: '전국의 분실물 정보를 한곳에서', link: '/search', tone: 'orange', label: '전국 통합 검색' },
];

export default function HomePage() {
  const { items, profile } = useApp();
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState<'all' | 'found' | 'lost'>('all');
  const navigate = useNavigate();
  const latest = items.filter(i => i.status === 'open' && (tab === 'all' || i.type === tab)).slice().reverse().slice(0, 4);
  const search = (e: FormEvent) => { e.preventDefault(); navigate(`/search?q=${encodeURIComponent(query.trim())}`); };
  return <>
    <section className="hero-section"><div className="page-container hero-grid"><div className="hero-copy"><div className="hero-eyebrow"><span><Sparkles size={13}/></span>기술로 찾고, 마음으로 연결하다</div><h1>잃어버린 소중함,<br/><span>다시 만나는 여정.</span></h1><p className="hero-description">전국의 분실물과 습득물을 한곳에서.<br/>AI와 이웃의 작은 친절이 당신의 일상을 찾아드려요.</p><form className="hero-search" onSubmit={search}><Search size={20}/><input aria-label="찾고 있는 물건" value={query} onChange={e => setQuery(e.target.value)} placeholder="어떤 물건을 찾고 계신가요?" maxLength={100}/><button type="submit" aria-label="물건 검색"><ArrowRight size={22}/></button></form><div className="popular-keywords"><span>많이 찾는 물건</span>{['지갑', '이어폰', '스마트폰', '가방'].map(k => <Link key={k} to={`/search?q=${encodeURIComponent(k)}`}>{k}<ArrowUpRight size={11}/></Link>)}</div></div>
      <div className="hero-visual" aria-label="분실물과 주인을 연결하는 탐색 일러스트"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-grid-pattern"/><div className="hero-visual-label"><span className="signal-dot"/>소중한 일상을 연결하는 중</div><svg className="hero-path" viewBox="0 0 500 380" fill="none" aria-hidden="true"><path d="M76 270C-20 160 171 120 242 208s193 118 175-35S274 14 275 89" stroke="#adc8e2" strokeWidth="2" strokeDasharray="6 8"/><circle cx="77" cy="270" r="7" fill="#76bfa9"/><circle cx="275" cy="89" r="5" fill="#2874ed"/></svg><div className="hero-object hero-wallet"><img src="/images/wallet.svg" alt="검은색 지갑 일러스트"/><span className="object-label"><span className="small-dot"/>찾고 있어요</span></div><div className="hero-object hero-earbuds"><img src="/images/earbuds.svg" alt="흰색 이어폰 일러스트"/><span className="object-label"><span className="small-dot green"/>주인을 기다려요</span></div><div className="hero-map-pin"><MapPin size={32} fill="currentColor" strokeWidth={1.4}/><span/></div><div className="hero-match"><span className="match-spark"><Sparkles size={20}/></span><div><small>소중한 물건을 발견했어요!</small><strong>AI 매칭 <em>92%</em></strong></div><span className="match-check"><Check size={15}/></span><span className="hero-demo-caption">시뮬레이션 예시</span></div><div className="hero-compass"><Fingerprint size={34} strokeWidth={1.2}/></div><div className="hero-caption"><span/>FIND IT. TOGETHER.</div></div>
    </div></section>
    <div className="page-container home-content"><section className="service-grid" aria-label="빠른 메뉴">{services.map(({ icon: Icon, title, text, link, tone, label }) => <Link to={link} className="service-card" key={link}><div className="service-top"><span className={`service-icon tone-${tone}`}><Icon size={25} strokeWidth={1.7}/></span><ArrowUpRight size={18}/></div><span className="service-label">{label}</span><h2>{title}</h2><p>{text}</p></Link>)}</section>
    <section className="recent-section"><div className="section-heading"><div><div className="section-kicker"><span className="small-dot green"/>다시 만날 수 있도록</div><h2>주인을 기다리는 소중한 물건들</h2><p>가까운 곳에서 당신의 물건이 기다리고 있을지 몰라요.</p></div><Link className="text-link" to="/search">전체 물품 보기<ArrowRight size={16}/></Link></div><div className="recent-toolbar"><div className="filter-pills" role="group" aria-label="물품 유형">{([['all', '전체'], ['found', '습득물'], ['lost', '분실물']] as const).map(([value, label]) => <button key={value} aria-pressed={tab === value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}</button>)}</div><Link className="nearby-link" to="/search?region=서울"><MapPin size={14}/>서울에서 찾기<ChevronRight size={13}/></Link></div><div className="items-grid">{latest.map(item => <ItemCard key={item.id} item={item}/>)}</div>{latest.length === 0 && <div className="empty-state"><Search size={32}/><h3>아직 등록된 물품이 없어요.</h3><Link to="/register" className="text-link">첫 물품 등록하기<Plus size={16}/></Link></div>}<p className="sample-caption">LOST QUEST 회원이 등록한 물품입니다.</p></section>
    <section className="ai-banner"><div className="ai-banner-icon"><ScanSearch size={34} strokeWidth={1.4}/><Sparkles size={15}/></div><div className="ai-banner-copy"><span>조금 더 똑똑한 분실물 찾기</span><h2>사진 한 장에서 시작되는 재회.</h2><p>색상, 종류, 발견 장소를 비교해 가장 닮은 물건을 추천해요.</p></div><Link to="/matches" className="button button-white">매칭 추천 보기<ArrowRight size={16}/></Link><span className="ai-banner-decoration"/></section>
    <section className="together-section"><div className="together-copy"><div className="section-kicker">작은 친절, 커다란 변화</div><h2>물건을 돌려주면,<br/>따뜻한 경험이 쌓여요.</h2><p>함께 찾고, 돌려주고, 성장하는 여정.<br/>반환 활동으로 경험치를 모으고 새로운 업적을 만나세요.</p><Link to="/mypage" className="text-link">나의 퀘스트 확인하기<ArrowRight size={16}/></Link></div><div className="quest-preview"><div className="quest-preview-top"><span className="quest-medal"><HeartHandshake size={27}/></span><div><small>오늘도 세상을 조금 더 따뜻하게</small><h3>당신도 누군가의 영웅이에요.</h3></div><span className="badge badge-blue">+50 XP</span></div><div className="quest-preview-bottom"><span className="level-circle">Lv.{Math.floor(profile.xp / 100) + 1}</span><div><div className="quest-progress-label"><strong>{profile.name}</strong><span>{profile.xp % 100} / 100 XP</span></div><div className="progress-track"><span style={{width: `${profile.xp % 100}%`}}/></div></div><span className="quest-star">✧</span></div><span className="quest-example">등록과 반환 활동에 따라 경험치가 지급돼요</span></div></section>
    <section className="help-strip"><span className="help-strip-icon"><CircleHelp size={22}/></span><div><strong>LOST QUEST가 처음이신가요?</strong><span>등록부터 반환까지, 이용 방법을 차근차근 알려드려요.</span></div><Link to="/guide">이용 안내<ArrowRight size={16}/></Link></section><div className="home-trust"><span><ShieldCheck size={15}/>비공개 특징으로 소유 확인</span><span><Sparkles size={15}/>AI 분석은 시뮬레이션</span><span><HeartHandshake size={15}/>함께 찾는 더 나은 일상</span></div>
    </div>
  </>;
}
